# Replace the text below to customize your site
site_name: Perustiedot tietojenkäsittelytieteen opiskelijalle
site_description: Tältä sivustolta löytyy kaikki tarvittava tieto, mitä Oulun yliopistossa aloittava tietojenkäsittelytieteen opiskelijan kannattaa tietokoneesta tietää. Ja vähän enemmän.

site_author: Joni Matias Rajala
docs_dir: docs
site_dir: _site
copyright: Creative Commons Attribution Non Commercial
theme:
  name: material
  # see https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    primary: "cyan"
    accent: "light blue"
  font:
    false
    # text: "Ubuntu"
    # code: "Ubuntu Mono"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
extra_javascript:
  - javascripts/extra.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra_css:
  - style.css


markdown_extensions:
  - extra
  - meta
  - smarty
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite


plugins:
  - search
  - awesome-nav
  - tags
  - charts